services:
  bot:
    image: mxr/faktatfrombaghdad
    container_name: FaktatfromBaghdad
    restart: unless-stopped
    volumes:
      - ./volume:/usr/src/faktatfrombaghdad/volume
      - ./GCC:/usr/src/faktatfrombaghdad/GCC
